import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import { AppProvider } from '@/providers/app-provider';
import { MainLayout } from '@/components/layout';

import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <MainLayout>{children}</MainLayout>
        </AppProvider>
      </body>
    </html>
  );
}
